# Generated by Django 4.1 on 2022-09-03 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id_producto_barra', models.AutoField(primary_key=True, serialize=False)),
                ('valor_licor', models.IntegerField()),
                ('valor_aco', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('localizacion', models.CharField(max_length=150)),
                ('suministro', models.CharField(max_length=150)),
                ('condicion_pago', models.CharField(max_length=50)),
                ('forma_contacto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha_venta', models.DateTimeField()),
                ('producto_barra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProFinalC3.barra')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('cantidad_producto', models.IntegerField()),
                ('existencia_producto', models.BooleanField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProFinalC3.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='barra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProFinalC3.producto'),
        ),
    ]
